---
- name: Restart postgresql
  become: true
  become_method: "{{ foremanctl_become_method | default('sudo') }}"
  become_user: "{{ foremanctl_user | default('root') }}"
  environment: "{{ foremanctl_runtime_env | default({}) }}"
  ansible.builtin.systemd:
    name: "{{ postgresql_container_name }}"
    state: restarted
    scope: "{{ postgresql_systemd_scope }}"
