---
- name: Setup rootless user environment
  import_playbook: ../setup-rootless-user/setup-rootless-user.yaml

# Play 2: Pull all container images in the foremanctl user context.
- name: Pull images
  hosts:
    - quadlet
  vars_files:
    - "../../vars/defaults.yml"
    - "../../vars/flavors/{{ flavor }}.yml"
    - "../../vars/images.yml"
    - "../../vars/base.yaml"
  become: true
  roles:
    - role: pre_install
  post_tasks:
    - name: Pull images as rootless user
      become: true
      become_method: "{{ foremanctl_become_method }}"
      become_user: "{{ foremanctl_user }}"
      environment: "{{ foremanctl_runtime_env }}"
      block:
        - name: Pull core images
          containers.podman.podman_image:
            name: "{{ item }}"
          loop: "{{ images }}"

        - name: Pull foreman_proxy images
          containers.podman.podman_image:
            name: "{{ item }}"
          loop: "{{ foreman_proxy_images }}"
          when:
            - "'foreman-proxy' in enabled_features"

        - name: Pull database images
          containers.podman.podman_image:
            name: "{{ item }}"
          loop: "{{ database_images }}"
          when:
            - database_mode == 'internal'
