---
- name: Check for unrecognized Smart Proxy features
  ansible.builtin.include_tasks: smart_proxy_features_check.yaml

- name: Configure registration defaults
  ansible.builtin.include_tasks: registration_defaults.yaml
  when:
    - "enabled_features | has_feature('remote-execution')"

- name: Post install message
  ansible.builtin.include_tasks: message.yaml

- name: Mark installation as complete
  ansible.builtin.copy:
    dest: "{{ post_install_done_flag }}"
    content: ''
    mode: '0640'
  delegate_to: localhost
  become: false
