---
- name: Configure Foreman systemd target as rootless user
  become: true
  become_method: "{{ foremanctl_become_method }}"
  become_user: "{{ foremanctl_user }}"
  environment: "{{ foremanctl_runtime_env }}"
  block:
    - name: Define foreman.target
      ansible.builtin.copy:
        dest: "{{ foremanctl_systemd_user_dir }}/foreman.target"
        mode: '0644'
        content: |
          [Unit]
          Description=Foreman services
          [Install]
          WantedBy=default.target

    - name: Run daemon reload to load new target
      ansible.builtin.systemd:
        daemon_reload: true
        scope: user

    - name: Start foreman.target
      ansible.builtin.systemd_service:
        name: foreman.target
        state: started
        enabled: true
        scope: user
