---
# This file runs as FOREMANCTL USER to create Podman secrets
# It reads from /var/lib/{{ foremanctl_user }}/tmp/ which was prepared by certs_prepare.yml
- name: Create the podman secret for Foreman CA certificate
  containers.podman.podman_secret:
    name: foreman-ca-cert
    path: "/var/lib/{{ foremanctl_user }}/tmp/foreman-ca-cert.crt"
    state: present
  notify:
    - Restart foreman
    - Restart dynflow-sidekiq@

- name: Create the podman secret for Foreman client certificate
  containers.podman.podman_secret:
    state: present
    name: foreman-client-cert
    path: "/var/lib/{{ foremanctl_user }}/tmp/foreman-client-cert.crt"
  notify:
    - Restart foreman
    - Restart dynflow-sidekiq@

- name: Create the podman secret for Foreman client key
  containers.podman.podman_secret:
    state: present
    name: foreman-client-key
    path: "/var/lib/{{ foremanctl_user }}/tmp/foreman-client-key.key"
  notify:
    - Restart foreman
    - Restart dynflow-sidekiq@
