---
- name: Ensure host registration settings directory exists
  ansible.builtin.file:
    path: /etc/foreman-proxy/settings.d
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: Render host registration settings
  ansible.builtin.template:
    src: settings.d/registration.yml.j2
    dest: /etc/foreman-proxy/settings.d/registration.yml
    mode: "0644"
    owner: root
    group: root
