---
- name: Generate custom certificates for testing
  hosts:
    - quadlet
  become: true
  vars:
    certificates_ca_directory: /root/custom-certificates
    certificates_ca_password: "CUSTOMCA"
    certificates_ca_subject: 'Custom Test CA'
    certificates_hostnames:
      - "{{ hostname | default(ansible_facts['fqdn']) }}"
    certificates_server_aliases: "{{ server_aliases | default([]) }}"
  roles:
    - role: certificates
