---
- name: Restart engine
  become: true
  become_method: "{{ foremanctl_become_method }}"
  become_user: "{{ foremanctl_user }}"
  environment: "{{ foremanctl_runtime_env }}"
  ansible.builtin.systemd:
    name: iop-core-engine
    state: restarted
    scope: user
