---
# This file runs as FOREMANCTL USER to create Podman secrets.
# It reads from /var/lib/foremanctl/tmp/ which was prepared by certs_prepare.yaml.
- name: Create Gateway server certificate secret
  containers.podman.podman_secret:
    state: present
    name: iop-core-gateway-server-cert
    path: "/var/lib/{{ foremanctl_user }}/tmp/iop-gateway-server-cert.pem"
  notify: Restart gateway

- name: Create Gateway server key secret
  containers.podman.podman_secret:
    state: present
    name: iop-core-gateway-server-key
    path: "/var/lib/{{ foremanctl_user }}/tmp/iop-gateway-server-key.pem"
  notify: Restart gateway

- name: Create Gateway server CA certificate secret
  containers.podman.podman_secret:
    state: present
    name: iop-core-gateway-server-ca-cert
    path: "/var/lib/{{ foremanctl_user }}/tmp/iop-gateway-server-ca-cert.pem"
  notify: Restart gateway

- name: Create Gateway client certificate secret
  containers.podman.podman_secret:
    state: present
    name: iop-core-gateway-client-cert
    path: "/var/lib/{{ foremanctl_user }}/tmp/iop-gateway-client-cert.pem"
  notify: Restart gateway

- name: Create Gateway client key secret
  containers.podman.podman_secret:
    state: present
    name: iop-core-gateway-client-key
    path: "/var/lib/{{ foremanctl_user }}/tmp/iop-gateway-client-key.pem"
  notify: Restart gateway

- name: Create Gateway client CA certificate secret
  containers.podman.podman_secret:
    state: present
    name: iop-core-gateway-client-ca-cert
    path: "/var/lib/{{ foremanctl_user }}/tmp/iop-gateway-client-ca-cert.pem"
  notify: Restart gateway
