---
- name: Deploy debug_tools
  ansible.builtin.include_role:
    name: debug_tools

- name: Install podman
  ansible.builtin.package:
    name:
      - podman

- name: Create containers config drop-in directory
  ansible.builtin.file:
    path: /etc/containers/containers.conf.d
    state: directory
    mode: '0755'

- name: Configure Podman to include host /etc/hosts entries
  ansible.builtin.copy:
    dest: /etc/containers/containers.conf.d/foremanctl.conf
    mode: '0644'
    content: |
      [containers]
      base_hosts_file = "/etc/hosts"

- name: Install other dependencies
  ansible.builtin.package:
    name:
      - bash-completion
      - python3-cryptography
      - python3-libsemanage
      - python3-psycopg2
      - python3-requests
      - python3-requests-oauthlib
