---
- name: Check /etc/subuid for rootless user
  ansible.builtin.command: grep "^{{ rootless_user_name }}:" /etc/subuid
  register: _check_subuid_subgid_subuid
  ignore_errors: true
  changed_when: false

- name: Check /etc/subgid for rootless user
  ansible.builtin.command: grep "^{{ rootless_user_name }}:" /etc/subgid
  register: _check_subuid_subgid_subgid
  ignore_errors: true
  changed_when: false

- name: Assert /etc/subuid and /etc/subgid have entries for {{ rootless_user_name }}
  ansible.builtin.assert:
    that:
      - _check_subuid_subgid_subuid is successful
      - _check_subuid_subgid_subgid is successful
    fail_msg: "Entries for user {{ rootless_user_name }} are missing in /etc/subuid or /etc/subgid"
