---
- name: Deploy Yuptoo container as rootless user
  become: true
  become_method: "{{ foremanctl_become_method }}"
  become_user: "{{ foremanctl_user }}"
  environment: "{{ foremanctl_runtime_env }}"
  block:
    - name: Pull Yuptoo container image
      containers.podman.podman_image:
        name: "{{ iop_yuptoo_container_image }}:{{ iop_yuptoo_container_tag }}"
        state: present

    - name: Deploy Yuptoo container
      containers.podman.podman_container:
        name: iop-core-yuptoo
        image: "{{ iop_yuptoo_container_image }}:{{ iop_yuptoo_container_tag }}"
        state: quadlet
        command: python -m main
        env:
          BOOTSTRAP_SERVERS: "iop-core-kafka:9092"
          BYPASS_PAYLOAD_EXPIRATION: "true"
        network:
          - iop-core-network
        quadlet_options:
          - |
            [Unit]
            Description=IOP Core Yuptoo Container
            [Service]
            Restart=on-failure
            [Install]
            WantedBy=default.target

    - name: Run daemon reload
      ansible.builtin.systemd:
        daemon_reload: true
        scope: user

    - name: Start Yuptoo service
      ansible.builtin.systemd:
        name: iop-core-yuptoo
        enabled: true
        state: started
        scope: user
