---
redis_container_image: quay.io/sclorg/redis-6-c10s
redis_container_tag: "latest"
redis_network: foreman-cache

# Container UID/GID for the redis process (used for podman unshare chown)
redis_container_uid: 1001
redis_container_gid: 1001
