---
- name: Restart Foreman Proxy
  become: true
  become_method: "{{ foremanctl_become_method }}"
  become_user: "{{ foremanctl_user }}"
  environment: "{{ foremanctl_runtime_env }}"
  ansible.builtin.systemd:
    name: foreman-proxy
    daemon_reload: true
    state: restarted
    scope: user

- name: Refresh Foreman Proxy
  theforeman.foreman.smart_proxy_refresh:
    smart_proxy: "{{ foreman_proxy_name }}"
    server_url: "{{ foreman_url }}"
    oauth1_consumer_key: "{{ foreman_oauth_consumer_key }}"
    oauth1_consumer_secret: "{{ foreman_oauth_consumer_secret }}"
    validate_certs: false
  failed_when: false
